### ISSUE TITLE
Richiesta upload file .bli per TG789vac Xtream 35b

### ISSUE THREAD

**Issue by mtrimarchi** [pietrotti97/pietrotti97.github.io#1]
Ciao @pietrotti97 ho trovato il tuo repository mentre cercavo su internet un file BLI (Bootloader Image) valido per il mio tg789vac v2. Ho visto che hai postato alcuni RBI (Remote BootLoader Image), purtroppo però da quanto ho visto non è possibile caricarli via TFTP al boot in quanto vengono rifiutati.

Ti allego un log qui sotto:

```
Technicolor Gateway
(c) 2015, All rights reserved

Gateway initialization sequence started
Boot Loader Version : 15.50.1005-0000000-20151209073757-4fd17452ef9fdf09e9f981340e5d6b3f85fe6c5a
Boot Loader OID     : unofficialbuildOID0000
CPU                 : BCM63138B0
RAM                 : 256MB
Flash               : 125MB NAND
Board Mnemonic      : VBNT-F
Market ID           : FFFC
Entering BOOT-P mode (reason: BUTTON_PUSH )
BOOTP Reply received
Local IP:        10.255.255.200
BOOTP Server IP: 10.255.255.254
TFTP Server IP:  10.255.255.254
Filename:        vant-6_16.3.7196-ver2.0.5-CRF592-2729004.rbi
TFTP started
*** 16159 kB received ***
TFTP finished
Booting from RAM
AES decryption failed
File is not a valid BLI
Resetting the gateway
```

Hai per caso un .bli da testare o una dritta da darmi?
Purtroppo questo è un router Fastweb con firmware custom per aziende e non trovo molte alternative oltre al flash via BOOT-P mode con TFTP.

Ciao e grazie!

**Comment by pietrotti97** [comment]
Ciao,
Da quello che vedo sul log che mi hai postato, il tuo non sembra essere un TG-789vacv2 ( board VANT-6) ma bensì un TG789vac XTREAM 35B ( board VBNT-F ) . Magari controlla cosa riporta sull'etichetta
Purtroppo per questo modem non ci sono firmware alternativi da testare, o almeno, io non ne ho trovati, ma da quello che so, se lo rooti riesci tranquillamente a installare la gui di ansuel e da li riesci a farci praticamente quello che vuoi.

**Comment by mtrimarchi** [comment]
Ciao, in effetti hai ragione. Non ho fatto caso all'etichetta e ho dato per scontato che fosse proprio il v2. Invece c'è scritto TG789vac Xtream 35b. Purtroppo non ho davvero idea di come procedere al root come da te indicato.

Se mi collego sulle porte LAN (quelle gialle) non ho nessuno scambio dati a livello di rete.
Se mi collego sulla WAN (quella rossa singola) allora mi risponde un DHCP Server che mi assegna un IP in classe 192.168.1.0/24. Ho accesso alla webgui tramite l'IP 192.168.1.254 ma mi chiede username e password e purtroppo le classiche note non funzionano (admin/admin - fastweb/vuoto - admin/ACCESSKEY presente in etichetta - etc.).

Hai qualche info da darmi in merito per caso?
Grazie mille!!!

**Comment by pietrotti97** [comment]
AH, è strano che le porte lan non rispondano. 
Hai provato a fare un reset dal tastino e veder cosa succede? Si comporta esattamente al contrario di come dovrebbe, sulla porta wan non dovrebbe rispondere un server dhcp. 
Magari le password sono state cambiate in passato, ma con un reset dovresti risolvere. 
Per il root ho trovato una guida non fatta da me, che potresti provare. Prima però devi riuscire ad entrare nella webui e almeno darmi la versione del firmware installata.

**Comment by mtrimarchi** [comment]
Sono agganciato in seriale sulla board direttamente (altrimenti il log di prima non lo avrei mai potuto estrarre). A quanto pare il tasto di reset non fa nessun reset.

Il comportamento è il seguente:
- se il router è già acceso esegue un reboot
- se il router è in fase di accensione, fa scattare il BOOT-P

Purtroppo è una situazione strana e non credo di avere molte soluzioni a disposizione.

**Comment by pietrotti97** [comment]
Ah, e per caso hai provato a tener premuto il testo reset tipo 10/20s ? 
Dico così per scrupolo, perchè non ho mai visto una cosa simile. 
In ogni caso, sempre dopo sto benedetto reset, con le credenziali scritte sull'etichetta dovresti riuscire ad entrare.

**Comment by mtrimarchi** [comment]
Ho provato svariate combinazioni in realtà. Dal classico 30-30-30 oppure tasto reset mentre è acceso per 60 secondi, piuttosto che tasto reset premuto all'avvio, etc.

Credo che il fatto che sia un router per una configurazione business (in cascata Fastweb aveva montato un Aethra SV6044E Series connesso sulla LAN, per questo la WAN viene usata come management) questo incide sul fatto che non si riesca a resettare in alcun modo.

Aggiungendo il fatto che su internet non trovo firmware alternativi, mi sa che non ho nessuna speranza di poterlo riconfigurare "a piacere".

**Comment by pietrotti97** [comment]
In un noto forum di adsl, ho trovato dei firmware per il tuo modem che potresti provare. 
Per caso durante il log dell'avvio riesci a capire che versione del firmware carica? Purtroppo ho trovato solo firmware fastweb, ma suppongo che una volta flashato con una versione più vecchia tu riesca a utilizzarlo normalmente. I firmware li carico sul repository, faccio una cartella apposita per il 789vac Xtream 

EDIT: non ho idea se il tuo sia IAD o MOS, e per scoprirlo credo dovresti entrare nella webui in qualche modo. in ogni caso i firmware dovrebbe caricarli lo stesso.

**Comment by mtrimarchi** [comment]
Te lo direi volentieri se riuscissi ad ottenere le credenziali 🙄 

Altro problema, quei file sono comunque .rbi e non .bli quindi non posso caricarli in fase di boot purtroppo.

**Comment by pietrotti97** [comment]
Carica tranquillamente pure quelli da BOOTP, che vanno bene. Non usare il tool di technicolor che è inutile. 

EDIT: usa il metodo che descrivo per caricare gli rbi su agtot che sono sicuro che funziona. Prima ti dava errore perchè stavi cercando di caricare un firmware di una board diversa, e giustamente lo rifiuta.

**Comment by mtrimarchi** [comment]
Hai perfettamente ragione.

```
Technicolor Gateway
(c) 2015, All rights reserved

Gateway initialization sequence started
Boot Loader Version : 15.50.1005-0000000-20151209073757-4fd17452ef9fdf09e9f981340e5d6b3f85fe6c5a
Boot Loader OID     : unofficialbuildOID0000
CPU                 : BCM63138B0
RAM                 : 256MB
Flash               : 125MB NAND
Board Mnemonic      : VBNT-F
Market ID           : FFFC
Entering BOOT-P mode (reason: BUTTON_PUSH )
BOOTP Reply received
Local IP:        10.255.255.200
BOOTP Server IP: 10.255.255.254
TFTP Server IP:  10.255.255.254
Filename:        16.2.7825-2349001-FW_212-MOS_TG789vacXtream.rbi
TFTP started
*** 24090 kB received ***
TFTP finished
Testing started
*** 47488 kB tested ***
Testing finished
Flashing started
*** 47488 kB programmed ***
Flashing finished
Resetting the gateway
----
```

Il firmware si è flashato, ma al boot ho ancora la versione di prima.

Ho paura che semplicemente il flash abbia avuto effetto sul Bank 2 ma di norma il sistema parte sul Bank 1.

Al riavvio difatti mi torna questo:

```
Technicolor Gateway
(c) 2015, All rights reserved

Gateway initialization sequence started
Boot Loader Version : 15.50.1005-0000000-20151209073757-4fd17452ef9fdf09e9f981340e5d6b3f85fe6c5a
Boot Loader OID     : unofficialbuildOID0000
CPU                 : BCM63138B0
RAM                 : 256MB
Flash               : 125MB NAND
Board Mnemonic      : VBNT-F
Market ID           : FFFC
Booting             : Bank 1
SW Version          : 16.2.7825-3401002-20170627172939-bca18a9e967f024980744d0bdc5476712638e931
Starting the Linux kernel

Enabling watchdog
Code Address: 0x00008000, Entry Address: 0x00008000
Decompression OK!
Entry at 0x00008000
Closing network.
Starting program at 0x00008000
```

Se guardi il SW Version è ancora **16.2.7825-3401002** nonostante io abbia caricato il **16.2.7825-2349001**.

**Comment by mtrimarchi** [comment]
Giuro, non ho capito cosa sia capitato ma ho tentato un secondo flash sempre con la stessa modalità e al riavvio ha cominciato a funzionare "normalmente"!!!

A quanto pare ora il DHCP server sulla LAN assegna gli IP come dovrebbe e sono riuscito ad accedere in webgui con user "Administrator" senza password!!!

![screenshot](https://user-images.githubusercontent.com/16150965/60124144-4a0a1800-9789-11e9-8410-706f7e264bd6.png)

**Comment by pietrotti97** [comment]
Ciao, 
è andata esattamente come hai detto. 
Al primo flash hai scritto il firmware sul secondo bank e si è riavviato sul primo bank, poi, al secondo flash l'hai scritto sul primo bank e al riavvio è partito il firmware che hai flashato ( perchè di default parte sempre dal primo bank) . 
Ora dovresti come prima cosa fare un reset dalla webui in modo da cancellare le variabili provenienti dal vecchio firmware e ripartire da zero. 
POI puoi provare a seguire questa guida (https://www.ilpuntotecnico.com/forum/index.php?topic=78382.0  , nono post)  per sbloccarlo e poi installare la gui di ansuel. 

Se riesci a installare la gui di ansuel poi puoi farci ciò che vuoi !

**Comment by mtrimarchi** [comment]
Yesssss!!!

Sono in SSH come root ora. Direi che posso davvero fare qualsiasi cosa adesso!

![screenshot](https://user-images.githubusercontent.com/16150965/60127167-d28bb700-978f-11e9-8a95-bf673e165bc5.png)

**Comment by pietrotti97** [comment]
OTTIMO
Hai seguito quella guida per il root suppongo. Se riesci a provare la gui di ansuel e darmi un feedback, poi provo a fare un how to nel sito! Per questo modem è tutto molto nebuloso, sarà che è poco diffuso, ma guide fatte bene per sbloccarlo non ne ho trovate purtroppo.

**Comment by mtrimarchi** [comment]
Ho utilizzato la versione 9.0.49 e sta funzionando.
Ci sono davvero svariati problemi in realtà con questa versione purtroppo.

Dalle informazioni sul router ho trovato questo:

Banco attivo **bank_1**
Versione attiva
_16.2.7825-3401002-20170627172939-bca18a9e967f024980744d0bdc5476712638e931_

Banco passivo **bank_2**
Versione passiva
_16.1.6849-2081003-20170302163937-4aec6f173b2ebf0c34ea39da71c3b8c6bc124f50_

Screenshot schede:

![image](https://user-images.githubusercontent.com/16150965/60293251-2c6eb700-991f-11e9-88bc-2abbfe8abee0.png)

**Comment by mtrimarchi** [comment]
Questo è il log dell'installazione:

```
root@OpenWrt:/tmp# /etc/init.d/rootdevice force
Root Script: Rooting in progress...
stopped ledfw.lua (pid 1076)
sh: ERROR       invalid path rpc.hosts.: bad number
stopped ledfw.lua (pid 5012)
sh: ERROR       invalid path rpc.hosts.: bad number
Warning: Unable to locate ipset utility, disabling ipset support
Warning: Option 'lan'.wan is unknown
Warning: Option 'mgmt'.wan is unknown
Warning: Section 'mgmt' cannot resolve device of network 'mgmt'
Warning: Option 'wan'.wan is unknown
Warning: Section 'wan' cannot resolve device of network 'wan'
Warning: Section 'wan' cannot resolve device of network '6rd'
Warning: Option 'wwan'.wan is unknown
Warning: Section 'wwan' cannot resolve device of network 'wwan'
Warning: Section 'SNAT_PING' has no src_dip option specified
Warning: Section @zone[1] (mgmt) has no device, network, subnet or extra options
Warning: Section @zone[2] (wan) has no device, network, subnet or extra options
Warning: Section @zone[3] (wwan) has no device, network, subnet or extra options
 * Flushing IPv4 filter table
 * Flushing IPv4 nat table
 * Flushing IPv4 mangle table
 * Flushing IPv4 raw table
 * Flushing IPv6 filter table
 * Flushing IPv6 mangle table
 * Flushing IPv6 raw table
 * Flushing conntrack table ...
 * Populating IPv4 filter table
   * Zone 'lan'
   * Zone 'mgmt'
   * Zone 'wan'
   * Zone 'wwan'
   * Rule 'Allow-DHCP-Renew'
   * Rule 'Allow-DHCP-Renew'
   * Rule 'Allow-Ping-mgmt'
   * Rule 'Allow-Ping-wan'
   * Rule 'Deny-CUPS-wan'
   * Rule 'Deny-CUPS-mgmt'
   * Rule 'Only-allow-access-to-LAN-IP'
   * Rule 'SSH_wan'
   * Rule 'Default action for outgoing NAT'
   * Forward 'lan' -> 'wan'
   * Forward 'lan' -> 'wwan'
 * Populating IPv4 nat table
   * Zone 'lan'
   * Zone 'mgmt'
   * Zone 'wan'
   * Zone 'wwan'
 * Populating IPv4 mangle table
   * Zone 'lan'
   * Zone 'mgmt'
   * Zone 'wan'
   * Zone 'wwan'
 * Populating IPv4 raw table
   * Zone 'lan'
   * Zone 'mgmt'
   * Zone 'wan'
   * Zone 'wwan'
 * Populating IPv6 filter table
   * Zone 'lan'
   * Zone 'mgmt'
   * Zone 'wan'
   * Zone 'wwan'
   * Rule 'Allow-DHCPv6'
   * Rule 'Allow-ICMPv6-Input'
   * Rule 'Allow-ICMPv6-Forward'
   * Rule 'Deny-CUPS-wan-v6'
   * Rule 'Deny-CUPS-mgmt-v6'
   * Rule 'Default action for outgoing NAT'
   * Forward 'lan' -> 'wan'
   * Forward 'lan' -> 'wwan'
 * Populating IPv6 mangle table
   * Zone 'lan'
   * Zone 'mgmt'
   * Zone 'wan'
   * Zone 'wwan'
 * Populating IPv6 raw table
   * Zone 'lan'
   * Zone 'mgmt'
   * Zone 'wan'
   * Zone 'wwan'
 * Set tcp_ecn to off
 * Set tcp_syncookies to on
   ! Unable to write value: No such file or directory
 * Set tcp_window_scaling to on
 * Running script '/etc/firewall.user'
 * Running script '/lib/functions/firewall-restart-ext-tch.sh'
 * Running script '/lib/functions/firewall-ext-tch.sh'
 * Running script '/lib/functions/tod.sh'
 * Running script '/usr/lib/intercept/firewall.sh'
 * Running script '/lib/functions/firewall-cwmpd.sh'
 * Running script '/lib/functions/firewall-igmpproxy-tch.sh'
 * Running script '/lib/functions/firewall-mldproxy-tch.sh'
 * Running script '/lib/functions/firewall-net-snmp.sh'
 * Running script '/usr/share/miniupnpd-tch/firewall.include'
 * Running script '/lib/functions/firewall-mmpbx.sh'
 * Running script '/lib/functions/weburl-tch.sh'
 * Running script '/lib/functions/firewall-dropbear.sh'
Root Script: Detected low flash space device...
start-stop-daemon: warning: killing process 3186: No such process
root@OpenWrt:/tmp#
```

**Comment by pietrotti97** [comment]
Ho letto il log, vedo qualche errore ma alla fine l'importante è che funzioni. 

Ho visto che hai 2 versioni diverse nelle due bank; per evitare problemi in futuro ti consiglio di andare in funzioni extra di sistema, e dare clona banco. In modo da avere i due bank identici. 

Se ti da problemi la gui puoi sempre toglierla/ se ci sono bug importanti puoi sempre segnalarle sul repo di ansuel. Per togliere la gui c'è l'opzione tra le impostazioni. 

Qui chiudo

**Comment by mtrimarchi** [comment]
Aprirò una segnalazione completa 😉

Grazie mille per l'aiuto!!! 🎉
